name: 使用Alist镜像测试功能
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: '下载URL'
        required: true
        default: 'https://网址##名称'
      Folder:
        description: '保存目录'
        required: true
        default: 'test'

jobs:
  TestforAlist:
    runs-on: ubuntu-latest
    services:
      alist:
        image: ykxvk8yl5l/alist-encrypt:dev
        env:
          DAV_PASSWORD: '123456'
    steps:
      - uses: actions/checkout@v2
      - name: Aria2 Install
        run:  sudo apt-get install -y aria2 
      - name: Downloading
        id: downloading
        run: |
          wget -O test http://alist:5344
          ls
          cat test
      
