name: 通过Alist上传
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      Url:
        description: '下载URL'
        required: true
        default: 'https://网址##名称'
      Folder:
        description: '保存目录'
        required: true
        default: 'encrypt_folder'

jobs:
  Alist:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      alist:
        image: xhofe/alist
        env:
          ALIST_ADMIN_PASSWORD: 'admin'
        ports:
        - 5244:5244
      alist-encrypt:
        image: ykxvk8yl5l/alist-encrypt:dev
        env:
          DAV_PASSWORD: '123456'
          DAV_ENCNAME: true
        ports:
        - 5344:5344
    steps:
      - uses: actions/checkout@v2
      - name: Aria2 Install
        run: apt-get update; apt-get install aria2 -y 
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install prerequisites
        run: |
          python -m pip install --upgrade pip wheel
          pip install install requests
      - name: Login
        id: login
        run: |
          alistauth=$(python alist.py --act='login')
          echo "$alistauth"
          echo "::set-output name=alistauth::$alistauth"
